version: "3.8"

services:
  mysqldb:
    platform: linux/arm64
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQLDB_PASSWORD"]
      interval: 20s
      timeout: 5s
      retries: 10
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: bookstore-service
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?autoReconnect=true&useSSL=false",
        "spring.datasource.username" : "${MYSQLDB_USERNAME}",
        "spring.datasource.password" : "${MYSQLDB_PASSWORD}",
        "spring.ai.azure.openai.api-key" : "${AZURE_AI_KEY}",
        "spring.ai.azure.openai.endpoint" : "${AZURE_AI_ENDPOINT}",
        "spring.ai.azure.openai.chat.options.model" : "${AZURE_AI_MODEL}",
        "spring.datasource.initialization-mode": "always"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
